repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.38.0"
    hooks:
      - id: eslint
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - eslint@^8.36.0
          - eslint-config-airbnb@^19.0.4
          - eslint-import-resolver-webpack@^0.13.2
          - eslint-plugin-import@^2.27.5
          - eslint-plugin-jsx-a11y@^6.7.1
          - eslint-plugin-react@^7.32.2
          - eslint-plugin-react-hooks@^4.6.0
          - "@typescript-eslint/eslint-plugin@^5.55.0"
          - "@typescript-eslint/parser@^5.58.0"
          - prettier@^2.8.7
          - eslint-config-prettier@^8.8.0
          - eslint-plugin-prettier@^4.2.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx]
